web:
  host: 127.0.0.1
  port: 8001
  name: George
  pass: George@1994

# 运行时Api前缀
api:
  prefix: /api

# Redis 缓存配置
redis:
  host: 127.0.0.1
  port: 6379
  pass:
  db: 1

# Kafka 配置
kafka:
  broker: 127.0.0.1:9092
  topic: websocketlogs

# Socket 路由
socket:
  prefix: /

# 运行时进程ID
runtime:
  pid: socket.lock

# SSL加密证书
ssl:
  cert: ssl/fullchain.cer
  key: ssl/betterde.com.key

# log
log:
  mongodb:
  host: 127.0.0.1
  port: 27017
  timeout: 600
  username:
  password:
  database: webim
  collection: websocketlogs

consul:
  enable: false
  host: 192.168.5.253
  port: 8500
  scheme: http
  datacenter: george

service:
  id:
  name: im
  tags:
    - 1.0.1
  check:
    uri: /health
    timeout: 1s
    interval: 2s
    deregister: 5s

debug: true