web:
  host: 127.0.0.1
  port: 8000
  name: George
  pass: George@1994

# 运行时Api前缀
api:
  prefix: /api

# Redis 缓存配置
redis:
  host: 10.29.87.219
  port: 6378
  pass:
  db: 1

# Kafka 配置
kafka:
  broker: 115.28.7.104:9092
  topic: websocketlogs

# Socket 路由
socket:
  prefix: /

# 运行时进程ID
runtime:
  pid: socket.lock

# SSL加密证书
ssl:
  cert: ssl/fullchain.cer
  key: ssl/betterde.com.key

# log
log:
  mongodb:
  host: 10.30.108.138
  port: 27018
  timeout: 600
  username:
  password:
  database: webim
  collection: websocketlogs