web:
  host: 127.0.0.1
  port: 8000
  name: George
  pass: George@1994
api:
  prefix: /api
redis:
  host: 127.0.0.1
  port: 6379
  pass:
kafka:
  broker: 10.66.157.147:9092
  topic: websocketlogs
socket:
  prefix: /ims
pid: socket.lock